const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Tally color scale
        tally: {
          gray: {
            1: '#fcfcfd',
            2: '#f2f4f7', 
            3: '#eaecf0',
            4: '#d0d5dd',
            5: '#98a2b3',
            6: '#667085',
            7: '#475467',
            8: '#344054',
            9: '#1d2939',
            10: '#101828',
            white: '#ffffff',
          },
          purple: {
            1: '#f7f4ff',
            2: '#ebe5ff',
            3: '#e0d6ff',
            4: '#beadff',
            5: '#9985ff',
            6: '#725bff',
            7: '#5749da',
            8: '#4b3cd8',
            9: '#372eb3',
            10: '#141466',
          },
          green: {
            1: '#f0fff9',
            2: '#cffceb',
            3: '#9ef0d3',
            4: '#71e3bf',
            5: '#49d6ae',
            6: '#25c9a1',
            7: '#15a384',
            8: '#0a7d68',
            9: '#03574a',
            10: '#01302b',
          },
          red: {
            1: '#fff0f0',
            2: '#ffe6e7',
            3: '#ffbdc2',
            4: '#ff94a0',
            5: '#ff6b81',
            6: '#f44061',
            7: '#cf2b4f',
            8: '#a81b3e',
            9: '#820e2f',
            10: '#5c0923',
          },
          orange: {
            1: '#fff1e3',
            2: '#ffe4c6',
            3: '#ffd6a4',
            4: '#ffc879',
            5: '#ffb800',
            6: '#e5a500',
            7: '#b28400',
            8: '#956f00',
            9: '#5e4200',
            10: '#251a00',
          },
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        // Tally border radius tokens
        'tally-square': '8px',
        'tally-button': '8px',
        'tally-container': '12px',
        'tally-tag': '4px',
      },
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans],
        brand: ['var(--font-brand)', ...fontFamily.sans],
      },
      fontSize: {
        // Tally typography scale
        'tally-1': '12px',
        'tally-2': '14px',
        'tally-3': '16px',
        'tally-4': '18px',
        'tally-5': '20px',
        'tally-6': '22px',
        'tally-7': '24px',
        'tally-8': '28px',
        'tally-9': '32px',
        'tally-10': '36px',
        'tally-11': '40px',
      },
      lineHeight: {
        // Tally line height scale
        'tally-1': '16px',
        'tally-2': '18px', 
        'tally-3': '20px',
        'tally-4': '22px',
        'tally-5': '24px',
        'tally-6': '28px',
        'tally-7': '32px',
        'tally-8': '36px',
        'tally-9': '40px',
        'tally-10': '44px',
        'tally-11': '48px',
      },
      spacing: {
        // Tally spacing scale
        'tally-0': '0px',
        'tally-1': '1px',
        'tally-2': '2px',
        'tally-3': '4px',
        'tally-4': '8px',
        'tally-5': '12px',
        'tally-6': '16px',
        'tally-7': '20px',
        'tally-8': '24px',
        'tally-9': '28px',
        'tally-10': '32px',
        'tally-11': '36px',
        'tally-12': '40px',
        'tally-13': '48px',
        'tally-14': '56px',
        'tally-15': '64px',
        'tally-20': '80px',
        'tally-30': '96px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}